### ISSUE TITLE
Issue with mutation count discrepancy between original and merged files

### ISSUE THREAD

**Issue by ulah** [ljdursi/mergevcf#1]
Hi,
First of all, thanks for the nice tool which hopefully save me some programming time for my current project. As an initial test I merged a gatk and a samtools/mpileup generated vcf file and wanted to check how many variants were called from both callers. The numbers of the individual counts, however, are larger in the merged file than in the original ones which doesn't make sense, but maybe I'm also misunderstanding something. So, I did the following:

Check the number of mutations in original gatk and samtools file and in the merged file, respectively:
$grep -v "^#" ./GATK.vcf | wc -l
766184
$grep -v "^#" ./Samtools_multiCall_S1to30.vcf | wc -l
3799788
$grep -v "^#" ./merged.vcf | wc -l
4180975

Now, I wrote a small script that simply parses:
Callers=GATK,Samtools
Callers=Samtools
in the merged.vcf and counts the single or muliple occurrences (Lines: 2, GATK: 1, GATKonly: 0, Samtools: 2, Samtoolsonly: 1, Combined: 1).

But when I apply this to the whole merged.vcf I get:
Lines:4180975
GATK:769026
GATKonly:345303
Samtools:3835672
Samtoolsonly:3411949
Combined:423723

So, the term "GATK" for example occurs slightly more often than there are mutations in the original vcf file...
What am I missing here?

Best regards,
Urs

**Comment by ljdursi** [comment]
I'll check to see if I can reproduce this.  Is there some public or synthetic data you see this in that can be used as a test case?

**Comment by ulah** [comment]
Yes, I have some public data for comparison included in my analysis, I have the same issue there. For example with sample SRR902865 (from the NCBI SRA):

$ zcat ../GATK/SRR902865.mapped.sorted.split.gatk.vcf.gz | grep -v "^#" | wc -l
22520
$ zcat ../Samtools/SRR902865.mapped.sorted.split.samtools.vcf.gz | grep -v "^#" | wc -l
86198
$ zcat ./mergedVCF.vcf.gz | grep -v "^#" | wc -l
100051

Lines:100051
GATK:22525
GATKonly:13810
Samtools:86241
Samtoolsonly:77526
Combined:8715

As the files are quite small, I'll sent them to your provided email address (Don't know how to upload them here...)

**Comment by ulah** [comment]
Ok, I have just installed Platypus as a third variant caller, run it on the sample and combined it once with the gatk and once with the samtools vcf's:

zcat ../GATK/SRR902865.mapped.sorted.split.gatk.vcf.gz | grep -v "^#" | wc -l
22520
$ zcat ../Samtools/SRR902865.mapped.sorted.split.samtools.vcf.gz | grep -v "^#" | wc -l
86198
zcat ../Platypus/SRR902865.mapped.sorted.split.platypus.vcf.gz | grep -v "^#" | wc -l
73104

With gatk and platypus I get:

zcat ./mergedVCF_gatk_platy.vcf.gz | grep -v "^#" | wc -l
25665

Lines:25665
GATK:22525
GATKonly:19553
Platypus:6112
Platypusonly:3140
Combined:2972

With samtools and platypus I get:

$ zcat ./mergedVCF_samtools_platy.vcf.gz | grep -v "^#" | wc -l
89815

Lines:89815
samtools:86241
samtoolsonly:83703
platypus:6112
platypusonly:3574
Combined:2538

So, the number of gatk and samtools entry is the same as before, which is fine. But where do I loose all the platypus entries? Maybe I'm also misunderstanding the output from mergevcf? So far I thought the "QUAL" and "FILTER" column are just dummy's as they are always "255" and "PASS". Does the program actually uses the "FILTER" column in the original vcf? My initial gatk and samtools vcf's aren't filtered at all and the respective column is therefore empty (i.e.: ".") - maybe this is causing problems?

**Comment by ljdursi** [comment]
Thanks for sending the test case.

So in the first case, GATK+Samtools, this is the result of multi-allelic calls being split so that each allele can be compared; for instance, looking at the GATK calls,

```
$ grep -v “^#" SRR902865.mapped.sorted.split.gatk.vcf | sort -k1,2n | awk '{print $1,$2,$4,$5}' > gatk.vars
$ grep -v “^#" mergedVCF.vcf | grep gatk.vcf | sort -k1,2n | awk '{print $1,$2,$4,$5}' > gatk-fm-merged.vars
$ diff gatk.vars gatk-fm-merged.vars
5506c5506,5507
< chr12 9453743 C A,G
---
> chr12 9453743 C A
> chr12 9453743 C G

18322c18323,18324
< chr6 31324536 T G,C
---
> chr6 31324536 T C
> chr6 31324536 T G
...
```

This is intentional, but might not always be desired behaviour.

Could you send the platypus calls as well, and I'll take a look at them?

**Comment by ulah** [comment]
Thanks for the clarification. I'm fine with it :)
The platypus calls are on the way.

**Comment by ljdursi** [comment]
Thanks for the other case!

With the platypus calls, many calls hadn't passed one or more filters, and those were filtered out during the merging.  I've added an option, `-f/--filtered`, to retain those calls.

Note that ideally the information about filters that have failed would be kept through the merging process; they are not currently.  I can add that, too, but that'll take a little doing.  Similarly with comparing multiallelic calls intact.  If either of those are important to you, you or I can add another issue explicitly requesting them as a feature request, and I can work on that next week.

**Comment by ulah** [comment]
Yes, I expected this to be the reason for platypus. The rest sounds great. Thanks a lot for the tool and fast help :)
I'll have to play a little with the output to see how it suits my purposes best; I may open another issue afterwards.
Best,
Urs
